name: build oses
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - oses/**
jobs:
  push:
    name: "pterodactyl:${{ matrix.oses }}-${{ matrix.platform }}"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        oses:
          - alpine
          - debian
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./oses/${{ matrix.oses }}
          file: ./oses/${{ matrix.oses }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/eriktma/pterodactyl:${{ matrix.oses }}-${{ matrix.platform }}
