name: build games
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - games/**
jobs:
  push:
    name: "games:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - source
          - rust
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
#          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./games/${{ matrix.game }}
          file: ./games/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/pterodactyl/games:${{ matrix.game }}
